import fs from "fs";
import path from "path";
import { Writable } from "stream";

type Collector = {
  ids: Set<string>;
  types: Set<string>;
  eoc_types: Set<string>;
  required_events: Set<string>;
  condition_keys: Set<string>;
  effect_keys: Set<string>;
  spawn_items: Set<string>;
  spawn_monsters: Set<string>;
  spells: Set<string>;
  missions: Set<string>;
  run_eocs: Set<string>;
};

function makeCollector(): Collector {
  return {
    ids: new Set(),
    types: new Set(),
    eoc_types: new Set(),
    required_events: new Set(),
    condition_keys: new Set(),
    effect_keys: new Set(),
    spawn_items: new Set(),
    spawn_monsters: new Set(),
    spells: new Set(),
    missions: new Set(),
    run_eocs: new Set(),
  };
}

function isObject(v: any): v is Record<string, any> {
  return v && typeof v === "object" && !Array.isArray(v);
}

function walkCondition(obj: any, collector: Collector) {
  if (!obj) return;
  if (Array.isArray(obj)) {
    obj.forEach((v) => walkCondition(v, collector));
    return;
  }
  if (!isObject(obj)) return;
  Object.keys(obj).forEach((k) => {
    collector.condition_keys.add(k);
    const v = (obj as any)[k];
    if (
      k === "compare_string" &&
      Array.isArray(v) &&
      typeof v[0] === "string"
    ) {
      // nothing extra
    }
    // Recurse into value
    walkCondition(v, collector);
  });
}

function walkEffectFragment(fragment: any, collector: Collector) {
  if (!fragment) return;
  if (Array.isArray(fragment)) {
    fragment.forEach((f) => walkEffectFragment(f, collector));
    return;
  }
  if (!isObject(fragment)) return;
  Object.keys(fragment).forEach((k) => {
    collector.effect_keys.add(k);
    const v = (fragment as any)[k];
    if (k === "u_spawn_item" && typeof v === "string")
      collector.spawn_items.add(v);
    if (k === "u_spawn_monster" && typeof v === "string")
      collector.spawn_monsters.add(v);
    if (
      (k === "u_cast_spell" || k === "npc_cast_spell") &&
      isObject(v) &&
      typeof v.id === "string"
    )
      collector.spells.add(v.id);
    if (k === "assign_mission" || k === "remove_active_mission") {
      if (typeof v === "string") collector.missions.add(v);
    }
    if (k === "run_eocs") {
      if (typeof v === "string") collector.run_eocs.add(v);
      else if (Array.isArray(v))
        v.forEach((id) => typeof id === "string" && collector.run_eocs.add(id));
      else if (isObject(v) && typeof v.id === "string")
        collector.run_eocs.add(v.id);
    }
    // recurse
    walkEffectFragment(v, collector);
  });
}

function processEoc(eoc: any, collector: Collector) {
  if (!isObject(eoc)) return;
  if (typeof eoc.id === "string") collector.ids.add(eoc.id);
  if (typeof eoc.type === "string") collector.types.add(eoc.type);
  if (typeof eoc.eoc_type === "string") collector.eoc_types.add(eoc.eoc_type);
  if (typeof eoc.required_event === "string")
    collector.required_events.add(eoc.required_event);
  if (eoc.condition) walkCondition(eoc.condition, collector);
  if (eoc.deactivate_condition)
    walkCondition(eoc.deactivate_condition, collector);
  if (eoc.effect) walkEffectFragment(eoc.effect, collector);
  if (eoc.false_effect) walkEffectFragment(eoc.false_effect, collector);
}

function readJsonFileSync(filePath: string): any | null {
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw);
  } catch (e) {
    return null;
  }
}

function walkDir(dir: string, collector: Collector) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let counter = 0;
  for (const ent of entries) {
    console.error(
      `Scanning ${++counter}/${entries.length} in ${dir}: ${ent.name}`,
    );
    const full = path.join(dir, ent.name);
    if (ent.isDirectory()) walkDir(full, collector);
    else if (ent.isFile() && ent.name.endsWith(".json")) {
      const parsed = readJsonFileSync(full);
      if (!parsed) continue;
      if (Array.isArray(parsed)) {
        parsed.forEach((e) => processEoc(e, collector));
      } else if (isObject(parsed) && Array.isArray((parsed as any).eocs)) {
        // some files may wrap in { eocs: [...] }
        (parsed as any).eocs.forEach((e: any) => processEoc(e, collector));
      }
    }
  }
}

function toArrayLiteral(set: Set<string>): string {
  return JSON.stringify(Array.from(set).sort(), null, 2);
}
function toIdentityEnumObject(set: Set<string>): string {
  const entries = Array.from(set).sort();
  const result: Record<string, string> = {};
  for (const v of entries) {
    result[v] = v;
  }
  return JSON.stringify(result, null, 2);
}

export async function generateDts(
  collector: Collector,
  outputStream: Writable,
) {
  const content = `// Generated by eoctool2 scan-constants
export const EOC_IDS = ${toArrayLiteral(collector.ids)} as const;
export type EOC_ID = typeof EOC_IDS[number];
export const EOC_ID_ENUM = ${toIdentityEnumObject(collector.ids)} as const;

export const EOC_TYPES = ${toArrayLiteral(collector.eoc_types)} as const;
export type EOC_TYPE = typeof EOC_TYPES[number];

export const TOP_LEVEL_TYPES = ${toArrayLiteral(collector.types)} as const;
export type TOP_LEVEL_TYPE = typeof TOP_LEVEL_TYPES[number];

export const REQUIRED_EVENTS = ${toArrayLiteral(collector.required_events)} as const;
export type REQUIRED_EVENT = typeof REQUIRED_EVENTS[number];

export const CONDITION_KEYS = ${toArrayLiteral(collector.condition_keys)} as const;
export type CONDITION_KEY = typeof CONDITION_KEYS[number];

export const EFFECT_KEYS = ${toArrayLiteral(collector.effect_keys)} as const;
export type EFFECT_KEY = typeof EFFECT_KEYS[number];

export const SPAWN_ITEMS = ${toArrayLiteral(collector.spawn_items)} as const;
export type SPAWN_ITEM = typeof SPAWN_ITEMS[number];

export const SPAWN_MONSTERS = ${toArrayLiteral(collector.spawn_monsters)} as const;
export type SPAWN_MONSTER = typeof SPAWN_MONSTERS[number];

export const SPELL_IDS = ${toArrayLiteral(collector.spells)} as const;
export type SPELL_ID = typeof SPELL_IDS[number];

export const MISSION_IDS = ${toArrayLiteral(collector.missions)} as const;
export type MISSION_ID = typeof MISSION_IDS[number];

export const RUN_EOC_IDS = ${toArrayLiteral(collector.run_eocs)} as const;
export type RUN_EOC_ID = typeof RUN_EOC_IDS[number];
`;
  await new Promise((resolve, reject) => {
    outputStream.write(content, (err) => {
      if (err) reject(err);
      else resolve(null);
    });
  });
}

export async function scanConstants(rootDir: string, stream: Writable) {
  const collector = makeCollector();
  walkDir(rootDir, collector);
  await generateDts(collector, stream);
  stream.end();
}
