# from enum import Enum


class Eocs:
    EOC_DRAIN_EFFECT_CHECK_HEADACHE = "EOC_DRAIN_EFFECT_CHECK_HEADACHE"
    EOC_PSIONICS_NETHER_ATTUNEMENT_CONSEQUENCES = (
        "EOC_PSIONICS_NETHER_ATTUNEMENT_CONSEQUENCES"
    )
    EOC_PSIONICS_GAIN_NETHER_ATTUNEMENT_SCALING_CHECK = (
        "EOC_PSIONICS_GAIN_NETHER_ATTUNEMENT_SCALING_CHECK"
    )
    EOC_PSIONICS_GAIN_NETHER_ATTUNEMENT = "EOC_PSIONICS_GAIN_NETHER_ATTUNEMENT"
    EOC_RAISE_ATTUNEMENT_ABOVE_THRESHOLD_CHECKER = (
        "EOC_RAISE_ATTUNEMENT_ABOVE_THRESHOLD_CHECKER"
    )
    EOC_RAISE_ATTUNEMENT_ABOVE_THRESHOLD = "EOC_RAISE_ATTUNEMENT_ABOVE_THRESHOLD"
    EOC_RAISE_ATTUNEMENT_BELOW_THRESHOLD_CHECKER = (
        "EOC_RAISE_ATTUNEMENT_BELOW_THRESHOLD_CHECKER"
    )
    EOC_RAISE_ATTUNEMENT_BELOW_THRESHOLD = "EOC_RAISE_ATTUNEMENT_BELOW_THRESHOLD"
    EOC_CONDITION_SPELLCASTING_FINISH_TRAIT_AND_SCHOOL_LIST = (
        "EOC_CONDITION_SPELLCASTING_FINISH_TRAIT_AND_SCHOOL_LIST"
    )
    pass


class Effects:
    PSIONIC_OVERLOAD = "psionic_overload"


class Vitamins:
    PSIONIC_DRAIN = "vitamin_psionic_drain"
    U_VITAMIN_PSIONIC_DRAIN = "u_vitamin('%s')" % PSIONIC_DRAIN


class U:
    LATEST_CHANNELED_POWER_DIFFICULTY = "u_latest_channeled_power_difficulty"

    class Vitamin:
        PSIONIC_DRAIN = "u_vitamin('%s')" % Vitamins.PSIONIC_DRAIN
